# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "RedNote"
name = "RedNote"
url = "https://www.xiaohongshu.com/user/profile/5efdc041000000000101de44?xsec_token=&xsec_source=pc_note"

[social.params]
icon = "brand-rednote"

[[social]]
identifier = "substack"
name = "Substack"
url = "https://substack.com/@kristineyuxi?utm_source=user-menu"

[social.params]
icon = "brand-substack"

[[social]]
identifier = "mediun"
name = "Medium"
url = "https://medium.com/@kristineyuxi"

[social.params]
icon = "brand-medium"

[[social]]
identifier = "wechat-public-account"
name = "Wechat-public-account"
url = "https://mp.weixin.qq.com/mp/appmsgalbum?__biz=MzIxMTE2MjIxMA==&action=getalbum&album_id=3455097328405790722#wechat_redirect"

[social.params]
icon = "微信公众号"

[[social]]
identifier = "rss"
name = "RSS"
url = "/index.xml"

[social.params]
icon = "brand-rss"

